name: planet
channels:
  - conda-forge
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=2.1.1
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - conda-pack=0.8.0
  - contourpy=1.0.5
  - cpython=3.8.20
  - cryptography=43.0.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - expat=2.7.1
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.13.3
  - fsspec=2024.6.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.1.0
  - harfbuzz=11.3.2
  - hpack=4.0.0
  - huggingface_hub=0.24.6
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp17=17.0.6
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcxx=21.1.5
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgpg-error=1.55
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm17=17.0.6
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=4.25.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.51.0
  - libtiff=4.7.0
  - libtorch=2.4.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm=17.0.6
  - llvm-openmp=19.1.7
  - lmdb=0.9.31
  - lz4-c=1.10.0
  - markupsafe=2.1.5
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nomkl=1.0
  - nspr=4.37
  - nss=3.117
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.46.4
  - platformdirs=4.3.6
  - ply=3.11
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python_abi=3.8
  - pytorch=2.4.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.15
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - sacremoses=0.0.53
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.8
  - stack_data=0.6.2
  - sympy=1.13.3
  - tk=8.6.13
  - tokenizers=0.12.1
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.19.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - et-xmlfile==2.0.0
      - openpyxl==3.1.5
      - pandas==2.0.3
      - pytz==2025.2
      - tzdata==2025.3
prefix: /Users/sindypinero/miniconda3/envs/planet
